
# --- !Ups

create table USER (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR NOT NULL,
  EMAIL_CONFIRMED BOOLEAN NOT NULL,
  NAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);

# --- !Downs

drop table USER;
