
# --- !Ups

create table ACCOUNT (
  ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  EMAIL_CONFIRMED BOOLEAN NOT NULL,
  NAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);

# --- !Downs

drop table ACCOUNT;
